# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('category', models.CharField(choices=[('产品质量', '产品质量'), ('网站使用', '网站使用'), ('支付购买', '支付购买'), ('客户服务', '客户服务')], max_length=20, verbose_name='分类')),
                ('username', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=200, verbose_name='邮箱')),
                ('screenshot', models.FileField(upload_to='', verbose_name='问题截图')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('subscription', models.BooleanField(default=True, verbose_name='订阅资讯')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('处理中', '处理中'), ('已处理', '已处理')], max_length=20, verbose_name='处理状态')),
                ('posted_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
        ),
    ]
