# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='备注说明'),
        ),
    ]
